version: '3.5'

services:
# Container management
  portainer_local:
    container_name: portainer_local
    image: portainer/portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - 9000:9000

volumes:
  portainer-data:
   name: portainer-data